import { useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { SectionCard } from '../components/SectionCard'
import { StatusBadge } from '../components/StatusBadge'

type IntelligenceItem = {
  category: string
  source: string
  title: string
  published_at: string
  url: string
  summary?: string
}

type IntelligencePayload = {
  window_start?: string
  window_end?: string
  generated_at_utc?: string
  generated_at_ct?: string
  items?: IntelligenceItem[]
}

function deriveUseLabel(item: IntelligenceItem): string {
  const source = item.source.toLowerCase()
  const category = item.category.toLowerCase()
  if (source.includes('ofac') || source.includes('fincen') || source.includes('treasury')) return 'Watch BSA/AML'
  if (source.includes('nacha') || source.includes('visa') || source.includes('mastercard') || category.includes('payment')) return 'Review payments'
  if (source.includes('occ') || source.includes('fdic') || source.includes('frb')) return 'Mgmt watchlist'
  if (category.includes('federal register')) return 'Plan change mgmt'
  if (category.includes('mortgage')) return 'Mortgage review'
  return 'Monitor trend'
}

export function IntelligencePage() {
  const [payload, setPayload] = useState<IntelligencePayload>({})
  const [enabledSources, setEnabledSources] = useState<Record<string, boolean>>({})

  useEffect(() => {
    fetch('/RegSmart/docs/data/items.json', { cache: 'no-store' })
      .then(async (response) => {
        if (!response.ok) throw new Error('Feed not available')
        return response.json() as Promise<IntelligencePayload>
      })
      .then((data) => setPayload(data))
      .catch(() => setPayload({ items: [] }))
  }, [])

  const allItems = payload.items ?? []

  const sourceStats = useMemo(() => {
    const stats = new Map<string, { source: string; category: string; count: number }>()
    allItems.forEach((item) => {
      const existing = stats.get(item.source)
      if (existing) existing.count += 1
      else stats.set(item.source, { source: item.source, category: item.category, count: 1 })
    })
    return Array.from(stats.values()).sort((a, b) => a.source.localeCompare(b.source))
  }, [allItems])

  useEffect(() => {
    setEnabledSources((current) => {
      const next = { ...current }
      sourceStats.forEach((item) => {
        if (!(item.source in next)) next[item.source] = true
      })
      return next
    })
  }, [sourceStats])

  const visibleItems = useMemo(
    () => allItems.filter((item) => enabledSources[item.source] !== false),
    [allItems, enabledSources]
  )

  return (
    <div>
      <PageHeader
        title="Regulatory Intelligence"
        subtitle="Live-source monitoring, source controls, and article intake for future issue, review, and watchlist workflows."
      />
      <div className="dashboard-grid">
        <SectionCard title="Source controls" subtitle="Turn individual sources on or off for this view.">
          <div className="source-grid">
            {sourceStats.map((item) => {
              const enabled = enabledSources[item.source] !== false
              return (
                <button
                  key={item.source}
                  type="button"
                  className={enabled ? 'source-toggle-card enabled' : 'source-toggle-card disabled'}
                  onClick={() => setEnabledSources((current) => ({ ...current, [item.source]: !enabled }))}
                >
                  <span>{item.source}</span>
                  <strong>{item.count} item(s)</strong>
                  <small>{item.category}</small>
                </button>
              )
            })}
          </div>
        </SectionCard>

        <SectionCard title="Intelligence articles" subtitle="Generated by build.py and loaded into the routed app.">
          {visibleItems.length === 0 ? (
            <div className="callout-box">
              <strong>No visible articles</strong>
              <p>Run <code>python build.py</code> from the repo root, then push the refreshed <code>docs/data/items.json</code>.</p>
            </div>
          ) : (
            <div className="table-shell">
              <table className="data-table">
                <thead>
                  <tr><th>Published</th><th>Source</th><th>Title</th><th>Category</th><th>Use</th></tr>
                </thead>
                <tbody>
                  {visibleItems.map((item) => (
                    <tr key={`${item.source}-${item.title}-${item.published_at}`}>
                      <td>{item.published_at}</td>
                      <td>{item.source}</td>
                      <td className="table-title-cell">
                        <strong><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a></strong>
                        <span>{item.summary ?? ''}</span>
                      </td>
                      <td><StatusBadge label={item.category} tone="info" /></td>
                      <td>{deriveUseLabel(item)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </SectionCard>
      </div>
    </div>
  )
}
